name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            echo ::set-output name=tag_name::${TAG}
            echo ::set-output name=version::${TAG%-*}
          else
            echo ::set-output name=version::snapshot
          fi
          echo ::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.build.outputs.platforms }}
      -
        name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      -
        name: Build
        run: |
          docker buildx build \
            --output "type=image,push=false" \
            --platform linux/amd64,linux/arm/v7 \
            --cache-from=type=registry,ref=kegbot/pycore \
            --cache-to=type=registry,ref=kegbot/pycore \
            --build-arg "BUILD_DATE=${{ steps.prepare.outputs.build_date }}" \
            --build-arg "GIT_SHORT_SHA=${GITHUB_SHA::8}" \
            --build-arg "VERSION=${{ steps.prepare.outputs.version }}" \
            --tag "kegbot/pycore:${{ steps.prepare.outputs.version }}" \
            --tag "kegbot/pycore:latest" \
            .
      -
        name: Publish
        if: success() && github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm/v7 \
            --cache-from=type=registry,ref=kegbot/pycore \
            --build-arg "BUILD_DATE=${{ steps.prepare.outputs.build_date }}" \
            --build-arg "GIT_SHORT_SHA=${GITHUB_SHA::8}" \
            --build-arg "VERSION=${{ steps.prepare.outputs.version }}" \
            --tag "kegbot/pycore:${{ steps.prepare.outputs.version }}" \
            --tag "kegbot/pycore:latest" \
            .